### ISSUE TITLE
Fehler im Script bei Ermittlung des reinen Hausverbrauchs

### ISSUE THREAD

**Issue by jansios** [ArnoD15/iobroker_E3DC#12]
Im Script ist an folgender Stelle ein < statt einem >

`// Funktion zur Berechnung der reinen Hausverbrauchsleistung
async function berechneReinenHausverbrauch() {
    try {
        let powerHome = (await getStateAsync(sID_Power_Home_W)).val;

        let leistungHeizstab = (sID_LeistungHeizstab_W) ? (await getStateAsync(sID_LeistungHeizstab_W)).val : 0;
        let wallboxLeistung1 = (sID_WallboxLadeLeistung_1_W) ? (await getStateAsync(sID_WallboxLadeLeistung_1_W)).val : 0;
        let wallboxLeistung2 = (sID_WallboxLadeLeistung_2_W) ? (await getStateAsync(sID_WallboxLadeLeistung_2_W)).val : 0;
        let leistungWaermepumpe = (sID_LeistungLW_Pumpe_W) ? (await getStateAsync(sID_LeistungLW_Pumpe_W)).val : 0;
        
        // Fehler abfangen das Wallbox sporadisch Leistungswerte über 35000 W übermittelt ohne das geladen wird
        **wallboxLeistung1 = (wallboxLeistung1 < 35000) ? wallboxLeistung1 : 0;`**

Dieser Fehler sorgt dafür, dass die Wallboxleistung immer gleich Null ist, so lange die Wallbox nicht 35000W oder mehr zieht. Das sorgt für einen falschen "reinen Hausverbrauch"

**Comment by ArnoD15** [comment]
Also ich kann keine Fehler finden.
Wenn diese Bedingung wahr ist "wallboxLeistung1 < 35000",  wird der Wert aus Variable "wallboxLeistung1" verwendet, was ja auch richtig ist.
Über die Modbus Schnittstelle werden sporadisch Ladeleistungen über 35000W übermittelt, obwohl nicht geladen wird.
Warum das so ist und ob das bei mir nur so ist, konnte ich nicht herausfinden. Damit fange ich diesen Fehler ab.
Ich habe diese Funktion aber komplett überarbeitet, da ich für Tibber den durchschnittlichen Verbrauch für den Tag und für die Nacht benötige. Wird mit der nächsten Version kommen.

**Comment by jansios** [comment]
Lustig, da hast Du irgendwie Recht - mit dem < hatte ich gestern den Effekt, dass die Wallbox-Leistung irgendwie ignoriert wurde, der reine errechnete Hausverbrauch war durchgehend 0, es wurde aus dem Netz gezogen und der Heizstab brummte. Habe ich das Zeichen auf ein > gedreht, klappte es so wie erwartet.

Woran kann das liegen?

Ich werde es weiter beobachten...

**Comment by ArnoD15** [comment]
War der errechnete Hausverbrauch 0 oder die wallboxLeistung ?
Der einzige Grund, warum der Hausverbrauch 0 sein kann ist, wenn die Leistung beim Hausverbrauch negativ ist, also mit einem minus davor.
Bei der Formel reinerHausverbrauch_W = powerHome - leistungHeizstab - wallboxLeistung1 - wallboxLeistung2 - leistungWaermepumpe
darf natürlich vom Wert powerHome nicht schon was abgezogen werden, wie z.B die Wallboxleistung.
Wenn bei dir da die Wallbox Leistung nicht mehr im Wert powerHome enthalten ist, darfst du die Wallboxleistung nicht noch mal abziehen.
Die Formel müsste dann so aussehen:
reinerHausverbrauch_W = powerHome - leistungHeizstab - leistungWaermepumpe

Kannst du das mal prüfen.

**Comment by jansios** [comment]
Es war definitiv der Hausverbrauch. Das passt aber zusammen - Bei einer E3DC-Wallbox wird ja die Leistung der Wallbox explizit angegeben und nicht im Hausverbrauch angezeigt. Dann war das mit dem <> eher ein Zufall, dass es danach passte, trotzdem komisch.

Ich lösche bei mir mal in der Berechnung die Wallbox-Leistung raus bzw. lasse die einfach oben als Feld leer, das dürfte ja den selben Effekt haben, dass sie nicht mehr abgezogen wird. Das Feld ist also nur für Fremd-Wallboxen zu füllen, die von E3DC als Hausverbrauch mitgezählt werden.

**Comment by ArnoD15** [comment]
> Fremd-Wallboxen zu füllen, die von E3DC als Hausverbrauch mitgezählt werden.

Richtig, oder E3DC-Wallboxen, die über Modbus angebunden sind.

**Comment by ArnoD15** [comment]
Ich werde das im Kommentar neben der Zeile vermerken.

**Comment by jansios** [comment]
Und damit kann die Issue dann auch geschlossen werden ;)
