### ISSUE TITLE
Reused variable 0_userdata.0.E3DC_Wallbox.Allgemein.Hausverbrauch

### ISSUE THREAD

**Issue by ORuessel** [ArnoD15/iobroker_E3DC#3]
**Describe the bug**  
In der Ansicht 28_E3DC_Uebersicht wird aus dem E3DC Wallbox Script ein userdata Objekt wiederverwendet, welches durch das Wallbox Script erstellt wird. 
0_userdata.0.E3DC_Wallbox.Allgemein.Hausverbrauch

**Expected behavior**  
Skript unterscheidet, ob die Wallbox vorhanden ist oder beide Skripte werden zusammengeführt, damit keine Überschreibungen der benötigten Werte durchgeführt werden.

Beispiel Abfrage, ob Parameter vorhanden und wenn nicht dann nutze sID_Power_Home_W

**Screenshots & Logfiles**  
If applicable, add screenshots and ioBroker Log-Files to help explain your problem.

![image](https://github.com/ArnoD15/iobroker_E3DC/assets/92107707/07f59729-c1cc-4bc1-9a27-ad19106b899e)

![image](https://github.com/ArnoD15/iobroker_E3DC/assets/92107707/21715822-029e-4259-9436-40284f39523e)

**Versions:**  
[iobroker_VIS_View_E3DC_Uebersicht.js](https://github.com/ArnoD15/iobroker_E3DC/blob/master/View%20Import%20Dateien%20VIS/iobroker_VIS_View_E3DC_Uebersicht.js)
https://github.com/ArnoD15/iobroker_E3DC/commit/8bc1da9d55b59707653625ab7ffd4687a997bc07

**Comment by ArnoD15** [comment]
Mein Vorschlag wäre hier eine neue Objekt-ID im Script Charge-Control anzulegen, die den reinen Hausverbrauch angibt.
Dazu würde ich variabel, ja nach dem, was ausgewählt wird, folgende Leistungen abziehen:
- Wallbox
- Heizstab
- Luftwärme Pumpe

@ORuessel du müsstest dann dein Script my-pv Heizstab.js anpassen und ich würde dein Script Hausverbrauch.js in das Script Charge-Control integrieren, mit der Erweiterung Wallbox und LW-Pumpe.

**Comment by ArnoD15** [comment]
In Charge-Control v. 1.4.1 umgesetzt.

**Comment by ArnoD15** [comment]
In Charge-Control v. 1.4.1 umgesetzt.
