### ISSUE TITLE
Uservariable in E3DC Overview verwendet, aber nicht vorhanden

### ISSUE THREAD

**Issue by ORuessel** [ArnoD15/iobroker_E3DC#4]
**Describe the bug**  
In der View 28_E3DC_UEBERSICHT wird für die Netzeinspeisung eine Variable und ein Balken verwendet. Leider ist im E3DC Wallbox, sowie im ChargeControl die variable 0_userdata.0.PV_Anlage.Zaehlerstaende.Netzeinspeisung_Jahr_Prozent nicht vorhanden bzw. wird eingesetzt.

**Expected behavior**  
1. Abhängigkeit wird für zukünftige Personen erläutert
2. Anpassungen der Sichtbarkeit für andere Personen die, die abhängigen Geräte verwenden
3. Bereitstellung in diesem oder anderem Repository das Script zur Berechnung

**Screenshots & Logfiles**  
![image](https://github.com/ArnoD15/iobroker_E3DC/assets/92107707/d09cdd7c-486f-4397-a13f-021222e680ce)

**Additional context**  
Welche der angebotenen Möglichkeiten soll verwendet oder angepasst werden ? Schließlich ist es die E3DC Übersicht.

**Comment by ArnoD15** [comment]
Dieser Balken zeigt die in das Netz eingespeiste Leistung übers Jahr in % an.
Ist ein Indikator, wie viel PV-Leistung nicht selber verbraucht werden kann bzw. noch für Optimierungen zur Verfügung stehen würde.
Um das zu berechnen, wird zusätzliche Hardware benötigt, um die Zählerstände vom Netzbezugszähler/Einspeisezähler zu erfassen.
Die Berechnung findet in einem eigenem Script statt, was eine tabellarische Übersicht über den Eigenverbrauch, Einspeisung, Bezugszähler, PV Zähler usw. erstellt.
Ich werde einen eigenen Ordner Zählerstände erstellen und das Script und die Views hochladen, dann kann jeder selber entscheiden, ob er es verwenden kann.

**Comment by ArnoD15** [comment]
Skript und die Views hochladen.
