### ISSUE TITLE
SG Ready

### ISSUE THREAD

**Issue by MichaelGer1410** [ArnoD15/iobroker_E3DC#6]
Hi, kannst du mir vielleicht sagen wie ich es hinbekomme das ich die SG Ready Funktion über VIS ein und ausschalten kann?
VG
Michael

**Comment by ORuessel** [comment]
@MichaelGer1410 im E3DC rscp Adapater gibt es aktuell keine Werte um die zu ermöglichen, daher kann dies ebenfalls nicht im VIS hinterlegt werden. Über Modbus können wir nur den SGReady Status anschauen. 

https://github.com/git-kick/ioBroker.e3dc-rscp/

**Comment by ArnoD15** [comment]
Das kann dann wohl geschlossen werden :-)

**Comment by MichaelGer1410** [comment]
> Das kann dann wohl geschlossen werden :-)

Jep 😁
