### ISSUE TITLE
Skript "mypv Heizstab.js": DebounceIntervall 3000 sorgt für Fehler

### ISSUE THREAD

**Issue by jansios** [ArnoD15/iobroker_E3DC#8]
Lasse ich den DebounceInterval auf 3000 wird der Heizstab nur alle 5min mit einem neuen Wert "beglückt und springt zwischenzeitlich auf 0 je nachdem was für ein Timeout Wert über die MyPV Cloud für das Gerät eingestellt ist. Setze ich ihn herunter auf 300 funktioniert das Skript wie erwartet.

**Comment by ArnoD15** [comment]
@ORuessel 
Kannst du dir das eventuell mal anschauen.

**Comment by ORuessel** [comment]
Hi @jansios hast du für mich eine Übersicht aller eingestellter Parameter ? Ich schaue mir das heute Abend im Büro mal genauer an.

**Comment by jansios** [comment]
Hi @ORuessel , ich habe wirklich nur diesen einen Parameter heruntergesetzt, mehr habe ich nicht angepasst. Na gut, oben die Pfade zu den Instanzen:

// defintion which instances has to be used 
const instanzE3DC_RSCP       = 'e3dc-rscp.0' 
const instanzHeizstab_Modbus = 'modbus.2'

Rest ist Standard wie im Download von Github

**Comment by ORuessel** [comment]
@jansios hast du ebenfalls das Hausverbrauchskript implementiert ? Hintergrund meiner Frage ist, der Debounceintervall ist nur ein Intervall, in welchem der Heizstab nicht mehrfach aktualisiert werden soll. 

Die Listener definieren, wann das Skript läuft.

    sID_PV_Leistung,
    sID_Netz_Leistung,
    sID_Eigenverbrauch,
    sID_Batterie_Leistung,
    sID_LeistungHeizstab_W,
    sID_M_Power_W,
    sID_Power_Mode,
    sID_Batterie_Status,
    sID_Batterie_Ladeende

**Comment by jansios** [comment]
Ja, das Skript läuft ebenfallsVon meinem iPhone gesendetAm 13.06.2024 um 21:49 schrieb ORuessel ***@***.***>:﻿
@jansios hast du ebenfalls das Hausverbrauchskript implementiert ? Hintergrund meiner Frage ist, der Debounceintervall ist nur ein Intervall, in welchem der Heizstab nicht mehrfach aktualisiert werden soll.
Die Listener definieren, wann das Skript läuft.
sID_PV_Leistung,
sID_Netz_Leistung,
sID_Eigenverbrauch,
sID_Batterie_Leistung,
sID_LeistungHeizstab_W,
sID_M_Power_W,
sID_Power_Mode,
sID_Batterie_Status,
sID_Batterie_Ladeende

**Comment by ORuessel** [comment]
@jansios  Welche Version von Charge_Control setzt du aktuell ein ? 
Kannst du mir die Informationen im Charge Control ausgeben, für die cons ?
const sID_Power_Home_W =

**Comment by ORuessel** [comment]
> Lasse ich den DebounceInterval auf 3000 wird der Heizstab nur alle 5min mit einem neuen Wert "beglückt und springt zwischenzeitlich auf 0 je nachdem was für ein Timeout Wert über die MyPV Cloud für das Gerät eingestellt ist. Setze ich ihn herunter auf 300 funktioniert das Skript wie erwartet.

Ich habe folgende Einstellung im my-pv Cloud für den Zeitablauf der Steuerung 

Zeitablauf Ansteuerung   62s

der E3DC RSCP holt alle 5 Sekunden einen neuen Wert von Power_Home ab. 

Ich habe auch um das 0 Watt beim Hausverbrauch zu testen, den Wert des Buffers (BUFFERSIZE) im Hausverbrauchsskripts auf 15 Werte erhöht.

**Comment by ArnoD15** [comment]
@ORuessel ich habe mir jetzt auch diesen Teil einmal angesehen und verstehe den debounceTimer nicht ganz.
Meiner Meinung nach kann es passieren, dass die 3 Sek. nie ablaufen, wenn sich eine der IDs innerhalb von 2 sek. ändert.
Da es mehrere IDs sind, ist es sogar ziemlich sicher, dass sich da jede sek. sogar eine ändert.
Wenn beispielsweise eine Änderung alle 2 Sekunden auftritt und der debounceTimer jedes Mal neu gesetzt wird, wird fetchAndUpdateHeizstabLeistung niemals ausgeführt, weil die 3-Sekunden-Frist nie erreicht wird oder übersehe ich da was?

Müsste das nicht so aussehen:
```
function debounceUpdate() {
    // Wenn der Timer bereits läuft, nichts tun (Timer wird nicht neu gesetzt)
    if (debounceTimer) return;

    // Erste Ausführung sofort, um schnelle Reaktionen zu ermöglichen
    fetchAndUpdateHeizstabLeistung();

    // Timer setzen, um nach dem Intervall weitere Updates zu ermöglichen
    debounceTimer = setTimeout(() => {
        debounceTimer = null;  // Nach Ablauf des Timers zurücksetzen, um neue Ausführungen zu ermöglichen
    }, debounceInterval);
}
```

**Comment by ArnoD15** [comment]
@jansios ich habe jetzt noch mal eine neue Version vom mypv Heizstab Skript hochgeladen, wo ich issues #8 und 9# mit berücksichtigt habe. 
Bitte die neue Version im Branch `Issue-10` vom mypv Heizstab Skript testen. :-)

**Comment by jansios** [comment]
Läuft, ich werde beobachten!

**Comment by jansios** [comment]
Was mir spontan auffällt ist, dass die eingestellte Reserve von 300W irgendwie nicht umgesetzt wird - es wird anscheinend immer eine Reserve von 1000W vorgehalten, bevor der Heizstab aktiviert wird. Aktuell sind keine 1000 Reserve verfügbar, aber auch von den z.T. knapp über 700W, die eingespeist werden, sollten eigentlich 400W an den Heizstab gehen:

`17.8.2024, 11:29:55.510	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1117W, PV=2823W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:29:55.667	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1117W, PV=2823W, Heizstab=0W, Überschuss=0W
17.8.2024, 11:29:59.561	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1193W, PV=2846W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:29:59.684	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1193W, PV=2846W, Heizstab=0W, Überschuss=0W
17.8.2024, 11:30:03.515	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1284W, PV=2880W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:30:03.702	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1284W, PV=2880W, Heizstab=0W, Überschuss=0W
17.8.2024, 11:30:07.647	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1345W, PV=2907W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:30:07.709	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1345W, PV=2907W, Heizstab=0W, Überschuss=0W
17.8.2024, 11:30:11.545	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1358W, PV=2932W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:30:11.680	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1358W, PV=2932W, Heizstab=0W, Überschuss=20.40000000000009W
17.8.2024, 11:30:15.547	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1415W, PV=2949W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:30:15.679	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1415W, PV=2949W, Heizstab=0W, Überschuss=37.40000000000009W
17.8.2024, 11:30:19.534	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Zustände abgefragt: Netz=-1445W, PV=2978W, Hausverbrauch=2611.6W, LeistungHeizstab=0W, Batterie=0W, IstTemp=57°C, MaxTemp=80.2°C, SollLeistungHeizstab=0W, PowerMode=0, BatterieStatus=47, Charge_Limit=9000, M_Power_W=0
17.8.2024, 11:30:19.665	[info ]: javascript.0 (198) script.js.Eigene_Skripte.Heizung.my-pv_Heizstab_Branch_10: Update: Netz=-1445W, PV=2978W, Heizstab=0W, Überschuss=66.40000000000009W`

`// Defintion von Heizstabparametern und Sicherheitsmechanismen
const debounceInterval          = 3000; // Minimum interval between updates in milliseconds
const temperatureBuffer         = 3;    // Buffer in degrees Celsius to prevent frequent on/off cycling
const minimumHeizstabLeistung   = 300;  // Minimum power for heating element
const sicherheitspuffer         = 300;  // Safety buffer to avoid frequent switching
const MaximalLeistungHeizstab_W = 3000; // Maximum power in watt of the heating element`

Der DebounceIntervall funktioniert jetzt korrekt, tatsächlich lief der bei mir vorher ins Leere, die 3000ms wurden nie erreicht. Ich musste den immer runtersetzen.

**Comment by jansios** [comment]
Und irgendwie klappt diese Code-Darstellung nicht bei mir, da waren echt Zeilenumbrüche sauber drin :(

**Comment by jansios** [comment]
Setze ich den "Sicherheitspuffer" auf -700, dann werden noch 300W eingespeist - so wie eigentlich gewünscht. Irgendwo stimmt da was noch nicht ganz

**Comment by ArnoD15** [comment]
Das kann leicht sein, denn M_Power_W ist die soll Ladeleistung was von ChargeControl eingestellt wird, E3DC regelt aber nie genau auf diese soll Leistung, sondern bleibt immer etwas darunter.
Leider konnte ich bis jetzt nicht feststellen, wie das bei E3DC berechnet wird, es ist auf jeden Fall kein linearer Verlauf.
Das kannst du in VIS an der Anzeige soll Ladeleistung ChargeControl und ist Ladeleistung E3DC gut verfolgen.

**Comment by ArnoD15** [comment]
> Und irgendwie klappt diese Code-Darstellung nicht bei mir, da waren echt Zeilenumbrüche sauber drin :(

Du musst drei ``` und ein Zeilenumbruch machen, damit das richtig angezeigt wird. Weiß aber auch nicht warum das so ist :-)

**Comment by jansios** [comment]
Das sind immer nur ein paar Watt Unterschied zwischen Ist und Soll, das kenne ich. Hier geht es aber um ziemlich genau 700W Abweichung. Eigentlich sollten es nach Einstellung 300W sein, die nicht für den Heizstab verwendet werden und dadurch eingespeist werden, es sind jedoch irgendwie min 1000W, die eingespeist werden. Setze ich den Sicherheitspuffer auf -700, also negativ, dann kommt es zur Einspeisung von 300W

**Comment by ArnoD15** [comment]
Kannst du mal anhand der LOG Ausgabe prüfen, ob die Berechnung:
let verfuegbarerUeberschuss_W = PV_Leistung_W - Hausverbrauch_W - M_Power_W- Wallbox_Leistung_W - sicherheitspuffer;
auch diesen unterschied, von 700 W hat und welcher Wert dazu führt.

Ich kann da leider nicht testen, da ich keinen Heizstab habe.

**Comment by jansios** [comment]
Habe die Ursache gefunden - im Skript stand als sID_Eigenverbrauch "0_userdata.0.Heizung.E3DC.Hausverbrauch_ohne_Heizstab" - Charge Control schreibt den aber in "0_userdata.0.Charge_Control.Allgemein.Hausverbrauch". Mit dem korrekten Wert läuft es so wie es soll.

**Comment by ArnoD15** [comment]
Ok, habe ich im Script geändert. Danke.
Dann können wir das Issue schließen?

**Comment by jansios** [comment]
Jep, passt so. Danke!
